---

- name: installing elasticsearch with version defined
  apt:
    name: elasticsearch={{ es_version }}
    state: present
  become: yes
  when: es_version is defined and es_version
  tags:
    - elasticsearch

- name: installing elasticsearch without version defined - default: latest
  apt:
    name: elasticsearch
    state: latest
  become: yes
  when: es_version is undefined or not es_version
  tags:
    - elasticsearch

- name: creating elasticsearch paths
  file:
    path: "{{ item }}"
    state: directory
    owner: elasticsearch
    group: elasticsearch
  with_items:
    - "{{ es_yml['path.data'] }}"
    - "{{ es_yml['path.logs'] }}"
  become: yes
  tags:
    - elasticsearch

- name: configuring elasticsearch
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    force: yes
    owner: elasticsearch
    group: elasticsearch
    mode: 0644
  with_items:
    - src: elasticsearch/elasticsearch.yml.j2
      dest: /etc/elasticsearch/elasticsearch.yml
    - src: elasticsearch/jvm.options.j2
      dest: /etc/elasticsearch/jvm.options
    - src: elasticsearch/log4j2.properties.j2
      dest: /etc/elasticsearch/log4j2.properties
  become: yes
  tags:
    - elasticsearch

- name: Get current plugins
  command: /usr/share/elasticsearch/bin/elasticsearch-plugin list
  register: installed_plugin_list
  become: yes
  when: es_install_plugins

- name: Uninstall plugins that need to be updated
  command: /usr/share/elasticsearch/bin/elasticsearch-plugin remove {{ item }}
  with_items: "{{ es_plugins }}"
  when: es_install_plugins and item in installed_plugin_list.stdout_lines
  become: yes

- name: Install/Update Plugins
  command: "/usr/share/elasticsearch/bin/elasticsearch-plugin install --batch {{ item }}"
  with_items: "{{ es_plugins }}"
  become: yes
  when: es_install_plugins

- name: starting elasticsearch
  service:
    name: elasticsearch
    state: restarted
    enabled: yes
  become: yes
  tags:
    - elasticsearch
