---

- name: installing filebeat
  apt:
    name: filebeat
    state: present
  become: yes
  tags:
    - filebeat

- name: configuring filebeat
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    force: yes
    owner: root
    group: root
    mode: 0644
  with_items:
    - src: filebeat/filebeat.full.yml.j2
      dest: /etc/filebeat/filebeat.full.yml
  become: yes
  tags:
    - filebeat

- name: starting filebeat
  service:
    name: filebeat
    state: started
    enabled: yes
  become: yes
  tags:
    - filebeat
