- name: download maxmind ppa
  apt_repository:
    repo: ppa:maxmind/ppa
  become: yes

- name: install geoipupdate
  apt:
    name: geoipupdate
    update_cache: yes
  become: yes

- name: copy geoipupdate config
  copy:
    src: "{{ role_path }}/files/GeoIP.conf"
    dest: "{{ ls_yml['path.geoipconfig'] }}"
  become: yes

- name: add cron job for geoipupdate
  cron:
    name: update_geoip
    weekday: "{{ ls_yml['config.geoipupdate_weekday'] }}"
    hour: "{{ ls_yml['config.geoipupdate_hour'] }}"
    minute: "{{ ls_yml['config.geoipupdate_minute'] }}"
    job: "/usr/bin/geoipupdate -v -f {{ ls_yml['path.geoipconfig'] }}"
  become: yes
