---

- name: installing kibana with version defined
  apt:
    name: kibana={{ kb_version }}
    state: present
  become: yes
  when: kb_version is defined and kb_version
  tags:
    - kibana

- name: installing kibana without version defined (default latest)
  apt:
    name: kibana
    state: latest
  become: yes
  when: kb_version is undefined or not kb_version
  tags:
    - kibana

- name: Updating kibana service to properly initialize kibana.pid (Bugfix)
  stat:
    path: /etc/init.d/kibana
  register: etc_initd

- stat:
    path: /bin/systemctl
  register: systemd_service

- lineinfile:
    dest: /etc/init.d/kibana
    line: '  touch $pidfile && chown $user:$group $pidfile'
    insertafter: '^\s*# Setup any environmental stuff beforehand$'
  become: yes
  when: etc_initd.stat.exists

- blockinfile:
    dest: /etc/systemd/system/kibana.service
    block: |
      PermissionsStartOnly=true
      ExecStartPre=/bin/touch {{ kb_yml['pid.file'] }}
      ExecStartPre=/bin/chown kibana:kibana {{ kb_yml['pid.file'] }}
    insertafter: '^\[Service\]'
  become: yes
  when: systemd_service.stat.exists

- systemd:
    name: kibana.service
    daemon_reload: yes
    enabled: yes
  become: yes
  when: systemd_service.stat.exists

- name: configuring kibana
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    force: yes
    owner: root
    group: root
    mode: 0644
  with_items:
    - src: kibana/kibana.yml.j2
      dest: /etc/kibana/kibana.yml
  become: yes
  tags:
    - kibana

- name: creating log directory for kibana
  file:
    path: "{{ kb_log_path }}"
    state: directory
    owner: kibana
    group: kibana
  become: yes
  when: kb_log_path is defined
  tags:
    - kibana

- name: Get list of installed Kibana plugins
  command: /usr/share/kibana/bin/kibana-plugin list
  register: kb_installed_plugins
  when: kb_install_plugins | bool
  become: yes

- name: Uninstall plugins for upgrade
  command: "/usr/share/kibana/bin/kibana-plugin remove {{ item.split('@')[0] }}"
  with_items: "{{ kb_installed_plugins.get('stdout_lines', None) }}"
  when: kb_install_plugins | bool
  become: yes

- name: Install/Upgrade plugins
  command: "/usr/share/kibana/bin/kibana-plugin install {{ item }}"
  with_items: "{{ kb_plugins }}"
  when: kb_install_plugins | bool
  become: yes

- name: Ensure correct permissions on kibana log
  file:
    path: "{{ kb_yml['logging.dest'] }}"
    state: touch
    owner: kibana
    group: kibana
  become: yes

- name: starting kibana
  service:
    name: kibana
    state: restarted
    enabled: yes
  become: yes
  tags:
    - kibana
