---

- name: installing kibana
  apt:
    name: kibana={{ db_version }}
    state: present
  become: yes
  when: kb_version
  tags:
    - kibana

- name: installing kibana
  apt:
    name: kibana
    state: latest
  become: yes
  when: not kb_version
  tags:
    - kibana

- name: configuring kibana
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    force: yes
    owner: root
    group: root
    mode: 0644
  with_items:
    - src: kibana/kibana.yml.j2
      dest: /etc/kibana/kibana.yml
  become: yes
  tags:
    - kibana

- name: creating pid file for kibana
  file:
    path: "{{ kb_yml['pid.file'] }}"
    state: touch
    owner: kibana
    group: kibana
  become: yes
  tags:
    - kibana

- name: creating log directory for kibana
  file:
    path: "{{ kb_log_path }}"
    state: directory
    owner: kibana
    group: kibana
  become: yes
  when: kb_log_path is defined
  tags:
    - kibana

- name: Installing Plugins
  command: "/usr/share/kibana/bin/kibana-plugin install {{ item }}"
  with_items: "{{ kb_plugins }}"
  become: yes
  when: kb_install_plugins

- name: starting kibana
  service:
    name: kibana
    state: started
    enabled: yes
  become: yes
  tags:
    - kibana
