---

- include: java.yml
  when: install_java

- include: apt.yml
  when: install_elasticsearch or install_logstash or install_beats or install_kibana

- include: elasticsearch.yml
  when: install_elasticsearch or install_kibana

- include: logstash.yml
  when: install_logstash

- include: beats.yml
  when: install_beats

- include: kibana.yml
  when: install_kibana
