---

- include: java.yml
  when: install_java

- include: git.yml
  when: install_git

- include: elastic-apt.yml
  when: install_elasticsearch or install_logstash or install_filebeat or install_kibana

- include: elasticsearch.yml
  when: install_elasticsearch

- include: python.yml
  when: install_python

- include: es-monitor.yml
  when: es_install_mapping_monitor

- include: logstash.yml
  when: install_logstash

- include: filebeat.yml
  when: install_filebeat

- include: kibana.yml
  when: install_kibana
